language: node_js
node_js:
  - "node"
sudo: false

install:
  - npm install
  - npm install -g codecov

jobs:
  include:
    - stage: test
      script: npm run test
      if: branch = master 
      script: codecov
