language: node_js
node_js:
  - "node"
sudo: false

install:
  - gem install compass
  - npm install -g gulp@4.0.0 typescript aurelia-cli gulp-sass gulp-compass
  - npm install
  - typings install
script:
  - gulp build-source
  - gulp sass
