// 
// @description : 
// @author      : Adarsh Pastakia
// @copyright   : 2017
// @license     : MIT
import {autoinject} from 'aurelia-framework';

@autoinject()
export class StyleGlyphs {
  constructor() { }

  // aurelia hooks
  canActivate(model) { return true; }
  activate(model) { return true; }
  bind(bindingContext) { }
  attached() { }
  detached() { }
  unbind() { }
  deactivate() { }
  // end aurelia hooks

  glyphs = {
    'Controls': [
      'bars-thin', 'bars-bold', 'ellipsis-v', 'ellipsis-v-line', 'ellipsis-h', 'ellipsis-h-line'
    ],
    'Arrows': [
      'arrow-circle-left-line', 'arrow-circle-right-line', 'arrow-circle-up-line', 'arrow-circle-down-line',
      'arrow-circle-left', 'arrow-circle-right', 'arrow-circle-up', 'arrow-circle-down',
      'arrow-left', 'arrow-right', 'arrow-up', 'arrow-down',
      'chevron-left', 'chevron-right', 'chevron-up', 'chevron-down',
      'chevron-left-2', 'chevron-right-2', 'chevron-up-2', 'chevron-down-2',
      'caret-left', 'caret-right', 'caret-up', 'caret-down'
    ],
    'Symbols': [
      'symbol-error',
      'symbol-error-line',
      'symbol-exclaim',
      'symbol-exclaim-bubble',
      'symbol-exclaim-line',
      'symbol-info',
      'symbol-info-bubble',
      'symbol-info-line',
      'symbol-question',
      'symbol-question-bubble',
      'symbol-question-line',
      'symbol-warning',
      'symbol-warning-line'
    ],
    'Icons': [
      'icon-add',
      'icon-add-line',
      'icon-alarm',
      'icon-alarm-line',
      'icon-anchor',
      'icon-anchor-line',
      'icon-barcode',
      'icon-bed',
      'icon-bed-line',
      'icon-bell',
      'icon-bell-line',
      'icon-building',
      'icon-building-line',
      'icon-calendar',
      'icon-calendar-line',
      'icon-clip',
      'icon-clip-line',
      'icon-clock',
      'icon-clock-line',
      'icon-coffee-cup',
      'icon-coffee-cup-line',
      'icon-cog',
      'icon-cog-line',
      'icon-comments',
      'icon-comments-line',
      'icon-dislike',
      'icon-dislike-line',
      'icon-division',
      'icon-division-line',
      'icon-download',
      'icon-download-line',
      'icon-download-cloud',
      'icon-download-cloud-line',
      'icon-edit',
      'icon-edit-line',
      'icon-email',
      'icon-email-line',
      'icon-equal',
      'icon-equal-line',
      'icon-fast-food',
      'icon-fast-food-line',
      'icon-female',
      'icon-female-line',
      'icon-filter',
      'icon-filter-line',
      'icon-folder',
      'icon-folder-line',
      'icon-folder-open',
      'icon-folder-open-line',
      'icon-heart',
      'icon-heart-line',
      'icon-help',
      'icon-help-line',
      'icon-home',
      'icon-home-line',
      'icon-image',
      'icon-image-line',
      'icon-key',
      'icon-key-line',
      'icon-like',
      'icon-like-line',
      'icon-link',
      'icon-link-line',
      'icon-location',
      'icon-location-line',
      'icon-lock',
      'icon-lock-line',
      'icon-meal',
      'icon-meal-line',
      'icon-message',
      'icon-message-line',
      'icon-minus',
      'icon-minus-line',
      'icon-notify',
      'icon-notify-line',
      'icon-page',
      'icon-page-edit',
      'icon-page-edit-line',
      'icon-page-line',
      'icon-page-search',
      'icon-page-search-line',
      'icon-palette',
      'icon-palette-line',
      'icon-parking',
      'icon-parking-line',
      'icon-pencil',
      'icon-pencil-line',
      'icon-pencil-ruler',
      'icon-pencil-ruler-line',
      'icon-phone',
      'icon-phone-line',
      'icon-placeholder',
      'icon-placeholder-line',
      'icon-printer',
      'icon-printer-line',
      'icon-qrcode',
      'icon-redo',
      'icon-redo-line',
      'icon-reload',
      'icon-reload-left',
      'icon-reload-left-line',
      'icon-reload-line',
      'icon-remove',
      'icon-remove-line',
      'icon-restaurant',
      'icon-restaurant-line',
      'icon-search',
      'icon-search-line',
      'icon-search2',
      'icon-search2-line',
      'icon-share',
      'icon-share-line',
      'icon-star',
      'icon-star-line',
      'icon-tea-cup',
      'icon-tea-cup-line',
      'icon-tools',
      'icon-tools-line',
      'icon-trash',
      'icon-trash-line',
      'icon-undo',
      'icon-undo-line',
      'icon-unlock',
      'icon-unlock-line',
      'icon-upload',
      'icon-upload-line',
      'icon-upload-cloud',
      'icon-upload-cloud-line',
      'icon-user',
      'icon-user-line',
      'icon-web',
      'icon-web-line',
      'icon-wifi',
      'icon-wifi-line'
    ],
    'Files': [
      'file-ai',
      'file-csv',
      'file-doc',
      'file-jpg',
      'file-mp4',
      'file-pdf',
      'file-png',
      'file-ppt',
      'file-psd',
      'file-tiff',
      'file-txt',
      'file-xls',
      'file-zip'
    ],
    'Social': [
      'social-dropbox',
      'social-dropbox-line',
      'social-facebook',
      'social-facebook-line',
      'social-gdrive',
      'social-gdrive-line',
      'social-google',
      'social-google-line',
      'social-instagram',
      'social-instagram-line',
      'social-linkedin',
      'social-linkedin-line',
      'social-skype',
      'social-skype-line',
      'social-snapchat',
      'social-snapchat-line',
      'social-twitter',
      'social-twitter-line',
      'social-whatsapp',
      'social-whatsapp-line',
      'social-youtube',
      'social-youtube-line'
    ]
  }
}